export const actionTypes = {
  // Users
  USER_LOGIN : "USER_LOGIN",
  EROR_LOGIN : "EROR_LOGIN",
  UPDATE_USER : "UPDATE_USER",
  GET_USERS : "GET_USERS",
  GET_SELECTED_USER : "GET_SELECTED_USER",
  CHANGE_VALUE: "CHANGE_VALUE",
  GET_USER: 'GET_USER',

  //Product
  ADD_CART : "ADD_CART"
}