import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import { Button } from '../components/atoms'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Styles className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Ini Contoh Buttonnya</h2>
      <h4>untuk propsnya pakai color="warnanya"</h4>
      <h5>nanti tinggal diatur height width dan ukuran font sizenya</h5>
      <div className="btn-collection">
          <Button className="button" color="shine">shine</Button>
          <Button className="button" color="choco">choco</Button>
          <Button className="button" color="white">white</Button>
          <Button className="button" color="gray">gray</Button>
          <Button className="button" color="choco-shadow">choco-shadow</Button>
          <Button className="button" color="shine-shadow">shine-shadow</Button>
          <Button className="button" color="white-choco">white-choco</Button> 
          <Button className="button" color="black">black</Button> 
      </div>
   
    </Styles>
  )
}
const Styles = styled.div`
.btn-collection{

  display: flex;
  flex-direction: row;
  gap: 15px;
  flex-wrap: wrap;
  justify-content: space-between;
  .button{
    width: 180px;
    height: 72px;
    font-size: 20px;
  }
}
  

`
